// Code generated by goctl. DO NOT EDIT!
// Source: ums.proto

package server

import (
	"context"

	"github.com/shrinex/shrinex-admin-backend/ums-rpc/internal/logic"
	"github.com/shrinex/shrinex-admin-backend/ums-rpc/internal/svc"
	"github.com/shrinex/shrinex-admin-backend/ums-rpc/pb"
)

type UmsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUmsServer
}

func NewUmsServer(svcCtx *svc.ServiceContext) *UmsServer {
	return &UmsServer{
		svcCtx: svcCtx,
	}
}

func (s *UmsServer) SignUp(ctx context.Context, in *pb.SignUpInput) (*pb.SignUpOutput, error) {
	l := logic.NewSignUpLogic(ctx, s.svcCtx)
	return l.SignUp(in)
}
